# Ivanica Gabriel 313CA

# Declarațiile de variabile
CC = gcc
CCFLAGS = -Wall -lm
SRC = tema2.c
PROGRAM = tema2

# Compilare
all:
	$(CC) -o $(PROGRAM) $(SRC) $(CCFLAGS)

.PHONY : clean
clean :
	rm -f $(PROGRAM) core *~
