# Ivanica Gabriel 313CA Tema4

# Declarațiile de variabile
CC = gcc
CCFLAGS = -Wall -lm
SRC = lf.c
PROGRAM = lf

# Compilare
all:
	$(CC) -o $(PROGRAM) $(SRC)


.PHONY : clean
clean :
	rm -f $(PROGRAM) core *~ 
