#   Target
PROGRAM_spu := tema3_spu
LIBRARY_embed := lib_tema3_spu.a

IMPORTS := -lmisc

# include partea care face toata treaba pe baza definitiilor de mai sus

ifdef CELL_TOP
            include $(CELL_TOP)/buildutils/make.footer
else
            include ../../../../buildutils/make.footer
endif
