# Ivanica Gabriel 313CA

# Declarațiile de variabile
CC = gcc
CCFLAGS = -Wall -O3 -Wno-unused-result
SRC = main.c hashtable.h
PROGRAM = tema3

# Compilare
all:
	$(CC) -o $(PROGRAM) $(SRC) $(CCFLAGS)

.PHONY : clean
clean :
	rm -f $(PROGRAM) core *~
