CC = gcc
CCFLAGS = -g -w -O3 -Wall

all: build

build:
	gcc $(CCFLAGS) Tema4.c -o Tema4

run:
	./Tema4

runt:
	./Tema4 google.com $(TYPE)

ptr:
	./Tema4 173.194.35.183 PTR

clean:
	rm -f Tema4
	rm -f *.o *~



